apiVersion: v1
kind: Pod
metadata:
  name: two-containers
  labels:
    example: two-containers
spec:

  volumes:
  - name: task-volume
    persistentVolumeClaim:
       claimName: task-pvc

  containers:

  - name: first
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts:
    - name: task-volume
      mountPath: /usr/share/nginx/html

  - name: second
    image: debian
    volumeMounts:
    - name: task-volume
      mountPath: /pod-data
    command: ["/bin/sh"]
    args:
      - "-c"
      - >
        while true; do
          date >> /pod-data/index.html;

          echo Hello from the second container >> /pod-data/index.html;
          sleep 30;
        done
---
apiVersion: v1
kind: Service
metadata:
  name: two-containers
spec:
  type: NodePort #Exposes the service as a node port
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    example: two-containers